steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Build Angular app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--', '--configuration=production']

  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/angular-app:$SHORT_SHA', '.']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/angular-app:$SHORT_SHA']

  # Invoke Cloud Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'angular-release-$SHORT_SHA'
      - '--project=$PROJECT_ID'
      - '--region=us-central1'
      - '--delivery-pipeline=angular-pipeline'
      - '--images=angular-app=gcr.io/$PROJECT_ID/angular-app:$SHORT_SHA'

images:
  - 'gcr.io/$PROJECT_ID/angular-app:$SHORT_SHA'
