steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build Angular app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--', '--configuration=production']

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/angular-app:$SHORT_SHA', '.']

  # Step 4: Push Docker image to Artifact Registry or GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/angular-app:$SHORT_SHA']

  # Step 5: Render the Cloud Deploy release config
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$SHORT_SHA'
      - '--delivery-pipeline=angular-app-pipeline'
      - '--region=us-central1'
      - '--images=angular-app=gcr.io/$PROJECT_ID/angular-app:$SHORT_SHA'

images:
  - 'gcr.io/$PROJECT_ID/angular-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
