trigger: none

pool:
  name: Default

variables:
- group: New variable group 22-May

steps:
- script: |
    echo "Fetching secrets from Vault..."
    
    # Install Vault CLI
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt update && sudo apt install -y vault

    # Export Vault env vars
    export VAULT_ADDR=$(VAULT_ADDR)
    export VAULT_TOKEN=$(VAULT_TOKEN)

    # Get secret
    vault kv get -field=USER_NAME secret/azure-creds
    vault kv get -field=SERVER_IP secret/azure-creds

  displayName: "Fetch Secrets from Vault"
