trigger:
- master

pool: Default

variables:
  VAULT_ADDR: $(VAULT_ADDR)

steps:
- script: |
    # Install Vault CLI if not already installed
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    sudo apt-get update && sudo apt-get install vault
  displayName: 'Install Vault CLI'

- script: |
    export VAULT_ADDR=$(VAULT_ADDR)
    export VAULT_ROLE_ID=$(ROLE_ID)
    export VAULT_SECRET_ID=$(SECRET_ID)

    # Authenticate with Vault using AppRole
    VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID)

    # Fetch secrets
    vault kv get -address=$VAULT_ADDR -token=$VAULT_TOKEN -format=json secret/myapp | jq '.data.data' > secrets.json

    # Set secrets as pipeline variables
    echo "##vso[task.setvariable variable=username]$(cat secrets.json | jq -r .username)"
    echo "##vso[task.setvariable variable=password]$(cat secrets.json | jq -r .password)"
  displayName: 'Fetch Secrets from Vault'

- script: |
    echo "Fetched Username: $(username)"
    echo "Fetched Password: $(password)"
  displayName: 'Use Fetched Secrets'








