steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Install Angular CLI globally
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', '@angular/cli@15.2.2']

  # Step 3: Run ng build (dev build)
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🏗️ Angular build starting..."
        ng build

  # Step 4: Optional — Show dist/ folder contents
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 dist/ folder:"
        find dist/

options:
  logging: CLOUD_LOGGING_ONLY








