# cloudbuild.yaml

steps:
  # 1. Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # 2. Build the Angular app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--', '--configuration=production']

  # 3. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/angular-app', '.'
    ]

  # 4. Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/angular-app']

  # 5. Deploy to Cloud Run (optional step)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'angular-app',
      '--image', 'gcr.io/$PROJECT_ID/angular-app',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/angular-app'
