steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Installing dependencies..."
        npm install

        echo "⚙️ Installing Angular CLI..."
        npm install -g @angular/cli@15.2.2

        echo "🏗️ Running ng build (dev)..."
        ng build

        echo "📁 Build complete. Listing dist/ folder..."
        ls -lh dist/
        echo "📁 Full build output files in dist/angularproject:"
        find dist/angularproject/ -type f

options:
  logging: CLOUD_LOGGING_ONLY










