steps:
  # 1. Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # 2. Build Angular app in production mode
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--', '--configuration=production']

options:
  logging: CLOUD_LOGGING_ONLY




