steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Install Angular CLI globally
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', '@angular/cli@15.2.2']

  # Step 3: Run ng build (default = dev build)
  - name: 'gcr.io/cloud-builders/nodejs'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ng version
        ng build

  # Step 4: Debug dist folder
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "✅ Files in dist/:"
        ls -lh dist/
        echo "📦 All files:"
        find dist/

options:
  logging: CLOUD_LOGGING_ONLY







